"use client";

import { formatINRPlain, formatStayDate, plural } from "@/lib/format";

export type ReceiptLine = { label: string; amount: number };

export type ReceiptInput = {
  reference: string;
  bookingId: number;
  status: string;
  paidAt?: string | null;
  paymentId?: string | null;
  guestName?: string | null;
  propertyTitle: string;
  propertyLocation: string;
  checkIn: string;
  checkOut: string;
  nights: number;
  guests: string;
  lines: ReceiptLine[];
  total: number;
  refund?: { amount: number; status?: string | null } | null;
};

/** Builds and downloads a PDF payment receipt for a booking. */
export async function downloadBookingReceipt(r: ReceiptInput) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const x = 16;
  const right = pageWidth - 16;
  let y = 22;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(0, 71, 114);
  doc.text("Hostiggo", x, y);
  doc.setFontSize(11);
  doc.setTextColor(90);
  doc.text("Payment receipt", right, y, { align: "right" });
  y += 12;

  doc.setDrawColor(220);
  doc.line(x, y, right, y);
  y += 10;

  const row = (label: string, value: string, bold = false) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setTextColor(bold ? 20 : 70);
    doc.text(label, x, y);
    doc.text(value, right, y, { align: "right" });
    y += 7;
  };

  doc.setFontSize(10);
  row("Booking reference", r.reference, true);
  row("Status", r.status);
  if (r.paidAt) {
    row(
      "Paid on",
      new Date(r.paidAt).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Kolkata" }),
    );
  }
  if (r.paymentId) row("Payment ID", r.paymentId);
  if (r.guestName) row("Guest", r.guestName);
  y += 4;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(20);
  const titleLines = doc.splitTextToSize(r.propertyTitle, right - x);
  doc.text(titleLines, x, y);
  y += 6 * titleLines.length;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90);
  if (r.propertyLocation) {
    doc.text(r.propertyLocation, x, y);
    y += 7;
  }
  doc.text(
    `${formatStayDate(r.checkIn)}  to  ${formatStayDate(r.checkOut)}  (${plural(r.nights, "night")}, ${r.guests})`,
    x,
    y,
  );
  y += 12;

  doc.setFontSize(10);
  for (const line of r.lines) row(line.label, formatINRPlain(line.amount));
  y += 1;
  doc.setDrawColor(200);
  doc.line(x, y - 4, right, y - 4);
  y += 2;
  doc.setFontSize(12);
  row("Total paid", formatINRPlain(r.total), true);

  if (r.refund && r.refund.amount > 0) {
    doc.setFontSize(10);
    row(`Refund${r.refund.status ? ` (${r.refund.status})` : ""}`, `- ${formatINRPlain(r.refund.amount)}`);
  }

  y += 10;
  doc.setFontSize(8.5);
  doc.setTextColor(130);
  doc.text(
    doc.splitTextToSize(
      "This receipt was generated by Hostiggo for a booking made on hostiggo.com. Amounts are in Indian Rupees and include applicable GST. For help, visit hostiggo.com/support.",
      right - x,
    ),
    x,
    y,
  );

  doc.save(`hostiggo-receipt-${r.reference}.pdf`);
}
