-- cancelBookingWithRefund() (src/lib/billing/cancelBooking.ts) writes here
-- whenever a guest cancels a booking whose payout has already been
-- released to the host -- the one case it deliberately does NOT
-- auto-refund via Razorpay (the money's already left the platform), instead
-- flagging it for a human in finance/ops to settle manually. The table
-- never existed, so hitting that branch threw an unhandled DB error instead
-- of actually flagging anything -- the cancellation would fail outright
-- rather than degrade to "flagged for manual settlement" as designed.
create table if not exists hostiggo_testing_schema.manual_settlement_flags (
  id bigint generated by default as identity primary key,
  booking_id integer not null references hostiggo_testing_schema.bookings(booking_id) on delete cascade,
  reason text not null,
  flagged_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid
);

create index if not exists manual_settlement_flags_booking_id_idx
  on hostiggo_testing_schema.manual_settlement_flags(booking_id);
