-- `booking_addons` was referenced by insertConfirmedBooking() and
-- addBookingAddon() (src/lib/services/admin-writes.ts, bookings.ts) but the
-- table never existed in this schema -- every insert into it silently
-- failed (caught and only console.error'd, non-fatal to the booking
-- itself), which meant the *total* a guest was charged always included
-- breakfast/other-services add-ons correctly, but the record of *which*
-- add-ons they bought was permanently lost, and the booking-confirmation
-- page's itemized invoice could never show those line items.
create table if not exists hostiggo_testing_schema.booking_addons (
  id bigint generated by default as identity primary key,
  booking_id integer not null references hostiggo_testing_schema.bookings(booking_id) on delete cascade,
  name text not null,
  price numeric not null default 0,
  type text,
  created_at timestamptz not null default now()
);

create index if not exists booking_addons_booking_id_idx
  on hostiggo_testing_schema.booking_addons(booking_id);
