-- Host-submitted payout details. Deliberately does NOT yet call any
-- Razorpay Route API (create Account / Stakeholder / product config) -- see
-- src/lib/services/hostPayouts.ts for why: Route's linked-account
-- onboarding is a real multi-step sub-merchant KYC process (business info,
-- PAN, address, bank details, document upload) that Razorpay itself has to
-- review and activate before any transfer would actually settle. This
-- table exists so a host can submit everything needed *once*, so that
-- onboarding step can be wired up later without asking them to re-enter
-- anything.
create table if not exists hostiggo_testing_schema.host_payout_methods (
  id bigint generated by default as identity primary key,
  host_uuid uuid not null references hostiggo_testing_schema.host(host_uuid) on delete cascade,

  -- Bank details -- Route's product/settlement config wants these on the
  -- linked account.
  account_holder_name text not null,
  bank_account_number text not null,
  bank_ifsc text not null,

  -- Route's Stakeholder API requires PAN for KYC -- not collected anywhere
  -- else in this app (the Aadhaar KYC flow is a separate identity check,
  -- not a tax/business KYC one).
  pan_number text not null,

  -- Registered/residential address -- required on both the Account and
  -- Stakeholder objects.
  address_line1 text not null,
  city text not null,
  state text not null,
  postal_code text not null,

  -- Never populated by this table on its own -- set only once the
  -- onboarding step described above actually runs.
  razorpay_account_id text,
  razorpay_stakeholder_id text,

  -- 'submitted'    -- host has filled the form; nothing sent to Razorpay yet.
  -- 'onboarding'   -- Razorpay Account/Stakeholder created, awaiting activation.
  -- 'active'       -- Razorpay has activated the account; transfers can be made.
  -- 'rejected'     -- Razorpay rejected the KYC; host needs to resubmit.
  status text not null default 'submitted'
    check (status in ('submitted', 'onboarding', 'active', 'rejected')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (host_uuid)
);

create index if not exists host_payout_methods_host_uuid_idx
  on hostiggo_testing_schema.host_payout_methods(host_uuid);
