-- Backs "Login activity" (src/app/account/login-activity/page.tsx), which
-- previously always rendered "No recent activity to show" -- there was no
-- table to record sign-ins into at all. Written to on every successful
-- sign-in (email OTP, phone OTP, password, Google) from the corresponding
-- server route.
create table if not exists hostiggo_testing_schema.login_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references hostiggo_testing_schema.users(user_id) on delete cascade,
  method text not null,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists login_events_user_id_created_at_idx
  on hostiggo_testing_schema.login_events(user_id, created_at desc);
